replicaCount: 4

image:
  repository: hardikroongta8/gatelog
  pullPolicy: IfNotPresent
  tag: "latest"

statefulSet:
  repository: mongo
  tag: "6.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

podLabels: {}

container:
  port: 4000

storage:
  size: 1Gi
  accessMode: ReadWriteOnce

volumeMounts:
  - name: mongodb-storage
    mountPath: "/data/db"
