apiVersion: v1
data:
  ADMIN_EMAIL: abc@def.com
  ADMIN_PANEL_COOKIE_SECRET: "1234"
  ADMIN_PASSWORD: "1234"
  BASE_URL: http://localhost:4000
  KHOKHA_SECURITY_KEY: key
  NODE_ENV: dev
  PORT: "4000"
  WEBSOCKET_CONNECTION_PATH: http://localhost:4000/ws
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-12T07:45:14Z"
  name: gatelog-config
  namespace: default
  resourceVersion: "21658"
  uid: 233fc048-e732-4bc4-a3f9-18bf9aecba66
