apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatelog.fullname" . }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "gatelog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gatelog.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "gatelog.serverPodSpec" . | nindent 6 }}
