apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatelog.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gatelog.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}