apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mongodb
  labels:
    app: {{ .Chart.Name }}-mongodb
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-mongodb
  ports:
    - port: 27017
      targetPort: 27017  