apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  serviceName: {{ .Release.Name }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: {{ .Release.Name }}-mongodb
        image: "{{ .Values.statefulSet.repository }}:{{ .Values.statefulSet.tag }}"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: {{ (index .Values.volumeMounts 0).name }}
            mountPath: {{ (index .Values.volumeMounts 0).mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: gatelog-data
    spec:
      accessModes: [{{ .Values.storage.accessMode }}]
      resources:
        requests:
          storage: {{ .Values.storage.size }}