apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-mongodb
spec:
  serviceName: {{ .Chart.Name }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mongodb
    spec:
      {{- include "gatelog.dbPodSpec" . | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: {{ (index .Values.volumeMounts 0).name }}
    spec:
      accessModes: [{{ .Values.storage.accessMode }}]
      resources:
        requests:
          storage: {{ .Values.storage.size }}